# Название файла: .github/workflows/build.yml

name: Kivy APK Builder

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # Этот шаг важен для правильной установки переменной ANDROID_HOME
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip install --upgrade cython
          pip install --upgrade buildozer

      - name: Build with Buildozer # <--- ИЗМЕНЕННЫЙ БЛОК
        run: |
          # Форсированно принимаем лицензии, создавая файлы вручную
          # Создаем директорию для лицензий
          mkdir -p $ANDROID_HOME/licenses
          
          # Записываем в файлы хэш-суммы, подтверждающие принятие лицензий
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
          echo "d975f751698a77b662f1254ddbeed3901e976f5a" > $ANDROID_HOME/licenses/intel-android-extra-license
          
          # А теперь запускаем саму сборку
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
