# Название файла: .github/workflows/build.yml

name: Kivy APK Builder

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Устанавливаем Java, чтобы переменная ANDROID_HOME была доступна
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip install --upgrade cython
          pip install --upgrade buildozer

      - name: Build with Buildozer # <--- ИСПРАВЛЕННЫЙ БЛОК
        run: |
          # Эта команда автоматически принимает все лицензии Android SDK
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # А уже после этого запускаем саму сборку
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
