# Название файла: .github/workflows/build.yml

name: Kivy APK Builder

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install buildozer and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip install --upgrade cython
          pip install --upgrade buildozer

      - name: Build with Buildozer (Two-Step Process)
        run: |
          # --- ШАГ 1: Запускаем сборку, чтобы она создала папки и упала (это нормально!) ---
          # Мы используем '|| true', чтобы ошибка с лицензией не остановила весь процесс
          buildozer -v android debug || true
          
          # --- ШАГ 2: Теперь, когда папки созданы, принудительно принимаем лицензии ---
          # Определяем точный путь к папке licenses, которую создал Buildozer
          LICENSE_DIR="/home/runner/.buildozer/android/platform/android-sdk/licenses"
          
          # Создаем саму папку, если вдруг она не появилась
          mkdir -p $LICENSE_DIR
          
          # Записываем в файлы хэш-суммы, подтверждающие принятие лицензий
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "${LICENSE_DIR}/android-sdk-license"
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > "${LICENSE_DIR}/android-sdk-preview-license"
          echo "d975f751698a77b662f1254ddbeed3901e976f5a" > "${LICENSE_DIR}/intel-android-extra-license"
          
          # --- ШАГ 3: Запускаем сборку снова. На этот раз она пройдет успешно. ---
          echo "Licenses accepted. Retrying build..."
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
